import { db } from "./index";
import {
  clinicSettings,
  users,
  doctors,
  services,
  patients,
  appointments,
  leads,
  reviews,
  blogPosts,
  faqs,
} from "./schema";
import { sql } from "drizzle-orm";

export async function seedDatabase() {
  try {
    // Check if doctors table has data
    const existingDoctors = await db.select({ count: sql<number>`count(*)` }).from(doctors);
    if (Number(existingDoctors[0]?.count || 0) >= 8) {
      console.log("Database already seeded with doctors.");
      return;
    }

    console.log("Starting comprehensive clinic seeding...");

    // 1. Clinic Settings
    const existingSettings = await db.select().from(clinicSettings).limit(1);
    if (existingSettings.length === 0) {
      await db.insert(clinicSettings).values({
        clinicName: "Medicare Plus Multi-Specialty Clinic",
        tagline: "Excellence in Specialized Healthcare & Modern Clinical Diagnostics",
        clinicType: "Multi-Specialty",
        phone: "+92 42 3578 9000",
        emergencyPhone: "+92 300 1122334",
        whatsapp: "+923001234567",
        email: "info@medicareplus.pk",
        address: "Plot 42-B, Main Boulevard, Gulberg III, Lahore, Pakistan",
        city: "Lahore",
        openingHoursWeekday: "Mon - Fri: 08:00 AM - 10:00 PM",
        openingHoursSaturday: "Saturday: 09:00 AM - 08:00 PM",
        openingHoursSunday: "Sunday: 10:00 AM - 04:00 PM (Emergency 24/7)",
        currency: "PKR",
        primaryColor: "#0f2b48",
        secondaryColor: "#0d9488",
        heroHeadline: "Leading Healthcare for You & Your Family in Lahore",
        heroSubheadline: "Board-certified consultants, international treatment protocols, cutting-edge diagnostic labs, and effortless same-day appointment scheduling.",
        aboutText: "Medicare Plus is Lahore's trusted healthcare destination. Established with a mission to combine empathetic patient care with top-tier medical expertise, our hospital provides clinical excellence across general medicine, cardiology, dermatology, dental surgeries, pediatrics, and physical therapy.",
      });
    }

    // 2. Doctors (8 Doctors with realistic Pakistani profiles)
    const doctorsData = [
      {
        name: "Dr. Ayesha Siddiqui",
        title: "Dr.",
        qualification: "MBBS, FCPS (Internal Medicine), MRCP (UK)",
        specialty: "General Physician",
        experienceYears: 14,
        fee: 2500,
        rating: "4.9",
        reviewsCount: 86,
        roomNo: "Room 101 - Executive OPD",
        bio: "Dr. Ayesha Siddiqui is a Senior Consultant Physician with extensive experience in diabetes management, hypertension, infectious diseases, and comprehensive preventative adult health checkups.",
        availableDays: "Mon,Tue,Wed,Thu,Fri,Sat",
        shiftStart: "09:00 AM",
        shiftEnd: "03:00 PM",
        slotDurationMinutes: 20,
        active: true,
        featured: true,
      },
      {
        name: "Dr. Muhammad Bilal",
        title: "Dr.",
        qualification: "BDS (KEMU), RDS, C-Implantology (USA), FCPS (Oral Surgery)",
        specialty: "Dental Surgery",
        experienceYears: 11,
        fee: 3000,
        rating: "4.9",
        reviewsCount: 112,
        roomNo: "Dental Suite 201",
        bio: "Dr. Bilal specializes in painless root canal treatments, cosmetic smile makeovers, dental implants, and surgical tooth extractions with state-of-the-art 3D imaging technology.",
        availableDays: "Mon,Tue,Wed,Thu,Sat",
        shiftStart: "11:00 AM",
        shiftEnd: "07:00 PM",
        slotDurationMinutes: 30,
        active: true,
        featured: true,
      },
      {
        name: "Dr. Zainab Tariq",
        title: "Dr.",
        qualification: "MBBS, MCPS, FCPS (Dermatology & Venereology)",
        specialty: "Dermatology & Aesthetics",
        experienceYears: 9,
        fee: 3500,
        rating: "5.0",
        reviewsCount: 94,
        roomNo: "Aesthetic Suite 104",
        bio: "Dr. Zainab is an acclaimed dermatologist specializing in clinical skin disorders, acne scar subcision, medical laser therapies, anti-aging solutions, and eczema treatment.",
        availableDays: "Mon,Wed,Thu,Fri,Sat",
        shiftStart: "02:00 PM",
        shiftEnd: "08:00 PM",
        slotDurationMinutes: 20,
        active: true,
        featured: true,
      },
      {
        name: "Dr. Farhan Malik",
        title: "Dr.",
        qualification: "MBBS, FCPS (Cardiology), Fellowship Interventional Cardiology",
        specialty: "Cardiology",
        experienceYears: 16,
        fee: 4000,
        rating: "4.9",
        reviewsCount: 78,
        roomNo: "Cardiology Clinic 302",
        bio: "Dr. Farhan Malik is an Interventional Cardiologist with vast experience in preventive cardiac care, 2D Echocardiography, hypertension management, and post-angioplasty care.",
        availableDays: "Tue,Wed,Thu,Fri",
        shiftStart: "10:00 AM",
        shiftEnd: "04:00 PM",
        slotDurationMinutes: 20,
        active: true,
        featured: true,
      },
      {
        name: "Dr. Sana Qureshi",
        title: "Dr.",
        qualification: "MBBS, DCH, FCPS (Pediatrics)",
        specialty: "Pediatrics & Child Care",
        experienceYears: 10,
        fee: 2500,
        rating: "4.8",
        reviewsCount: 65,
        roomNo: "Pediatric Wing 105",
        bio: "Dr. Sana provides compassionate healthcare for infants, toddlers, and adolescents including routine vaccinations, nutritional growth assessments, and seasonal pediatric illnesses.",
        availableDays: "Mon,Tue,Wed,Thu,Fri,Sat",
        shiftStart: "09:00 AM",
        shiftEnd: "02:00 PM",
        slotDurationMinutes: 15,
        active: true,
        featured: true,
      },
      {
        name: "Dr. Usman Khalid",
        title: "Dr.",
        qualification: "MBBS, DOMS, FCPS (Ophthalmology), Vitreo-Retinal Fellow",
        specialty: "Ophthalmology / Eye Care",
        experienceYears: 13,
        fee: 3000,
        rating: "4.9",
        reviewsCount: 52,
        roomNo: "Eye Care Suite 203",
        bio: "Expert ophthalmologist specialized in computerized vision checks, phaco-cataract surgery, glaucoma monitoring, and pediatric eye screenings.",
        availableDays: "Mon,Tue,Thu,Fri",
        shiftStart: "01:00 PM",
        shiftEnd: "06:00 PM",
        slotDurationMinutes: 20,
        active: true,
        featured: false,
      },
      {
        name: "Dr. Fatima Noor",
        title: "Dr.",
        qualification: "DPT (Doctor of Physical Therapy), MS-OMPT, Certified Dry Needling",
        specialty: "Physiotherapy & Rehab",
        experienceYears: 8,
        fee: 2200,
        rating: "4.9",
        reviewsCount: 71,
        roomNo: "Rehab & Physio Lab",
        bio: "Specialist in musculoskeletal rehabilitation, sports injury recovery, chronic back & neck pain management, and post-operative mobility therapy.",
        availableDays: "Mon,Tue,Wed,Thu,Fri,Sat",
        shiftStart: "10:00 AM",
        shiftEnd: "06:00 PM",
        slotDurationMinutes: 40,
        active: true,
        featured: false,
      },
      {
        name: "Dr. Hamza Raza",
        title: "Dr.",
        qualification: "MBBS, MS (General Surgery), MRCS (Edin)",
        specialty: "General & Laparoscopic Surgery",
        experienceYears: 15,
        fee: 3500,
        rating: "4.8",
        reviewsCount: 43,
        roomNo: "Surgical OPD 108",
        bio: "Renowned surgical specialist offering minimally invasive laparoscopic procedures, hernia repair, gallbladder surgery, and minor OPD surgical care.",
        availableDays: "Mon,Wed,Fri,Sat",
        shiftStart: "03:00 PM",
        shiftEnd: "07:00 PM",
        slotDurationMinutes: 20,
        active: true,
        featured: false,
      },
    ];

    const insertedDoctors = await db.insert(doctors).values(doctorsData).returning();

    // 3. User Accounts (Section 39)
    await db.insert(users).values([
      {
        name: "Super Admin",
        email: "admin@medicareplus.demo",
        password: "Admin@12345",
        role: "super_admin",
        phone: "+92 300 1234567",
        active: true,
      },
      {
        name: "Receptionist Maryam",
        email: "reception@medicareplus.demo",
        password: "Reception@12345",
        role: "receptionist",
        phone: "+92 321 4455667",
        active: true,
      },
      {
        name: "Dr. Ayesha Siddiqui",
        email: "doctor@medicareplus.demo",
        password: "Doctor@12345",
        role: "doctor",
        doctorId: insertedDoctors[0]?.id || 1,
        phone: "+92 333 7788990",
        active: true,
      },
    ]);

    // 4. Services (15 Services across Pakistani clinical departments)
    const servicesData = [
      {
        name: "General Physician Consultation",
        category: "General Medicine",
        description: "Comprehensive medical evaluation, blood pressure assessment, clinical history review, and personalized treatment plan.",
        durationMinutes: 20,
        price: 2500,
        icon: "Stethoscope",
        badge: "Popular",
        preparationInstructions: "Please bring your previous medical records, blood reports, and current medication list.",
        active: true,
        featured: true,
      },
      {
        name: "Executive Health Checkup Package",
        category: "General Medicine",
        description: "Complete full-body profile: Fasting Glucose, Lipid Profile, LFT, RFT, CBC, Chest X-ray, ECG, and Doctor Consultation.",
        durationMinutes: 45,
        price: 9500,
        icon: "HeartPulse",
        badge: "Comprehensive",
        preparationInstructions: "Requires 10-12 hours of overnight fasting before laboratory sample collection.",
        active: true,
        featured: true,
      },
      {
        name: "Teeth Scaling & Polishing",
        category: "Dental Care",
        description: "Ultrasonic tartar removal, plaque cleaning, stain polishing, and gum health assessment for a sparkling, healthy smile.",
        durationMinutes: 30,
        price: 4500,
        icon: "Sparkles",
        badge: "Best Value",
        preparationInstructions: "Brush your teeth 30 minutes before your appointment.",
        active: true,
        featured: true,
      },
      {
        name: "Root Canal Treatment (Single Tooth)",
        category: "Dental Care",
        description: "Modern single-visit painless motorized root canal therapy to preserve badly decayed or infected teeth.",
        durationMinutes: 45,
        price: 12000,
        icon: "ShieldAlert",
        badge: "Pain-Free",
        preparationInstructions: "Have a light meal prior to local anesthesia administration.",
        active: true,
        featured: false,
      },
      {
        name: "Cosmetic Dental Fillings",
        category: "Dental Care",
        description: "High-grade shade-matched composite aesthetic tooth fillings for chips, cavities, and cosmetic gaps.",
        durationMinutes: 30,
        price: 3500,
        icon: "Smile",
        badge: "Natural Look",
        preparationInstructions: "None required.",
        active: true,
        featured: false,
      },
      {
        name: "Clinical Dermatology Consultation",
        category: "Dermatology",
        description: "Diagnostic assessment for acne, melasma, psoriasis, fungal allergies, hair loss (alopecia), and chronic rashes.",
        durationMinutes: 20,
        price: 3500,
        icon: "UserCheck",
        badge: "Specialist",
        preparationInstructions: "Avoid wearing heavy makeup or cosmetic foundation on facial areas to be examined.",
        active: true,
        featured: true,
      },
      {
        name: "HydraFacial Glow Treatment",
        category: "Dermatology",
        description: "Medical-grade 7-step vortex exfoliation, deep pore blackhead extraction, antioxidant hydration, and LED light therapy.",
        durationMinutes: 60,
        price: 8500,
        icon: "Sparkles",
        badge: "Most Booked",
        preparationInstructions: "Avoid retinol products and direct intense sun exposure 48 hours prior.",
        active: true,
        featured: true,
      },
      {
        name: "Cardiology Consultation & ECG",
        category: "Cardiology",
        description: "Resting 12-Lead Electrocardiogram with immediate interpretation by Senior Interventional Cardiologist.",
        durationMinutes: 30,
        price: 5000,
        icon: "Activity",
        badge: "Critical Care",
        preparationInstructions: "Wear comfortable loose shirt with easy chest access. Avoid heavy caffeine 2 hours before.",
        active: true,
        featured: true,
      },
      {
        name: "2D Color Doppler Echocardiography",
        category: "Cardiology",
        description: "High-resolution ultrasound imaging of heart chambers, cardiac muscle contractility, and heart valve function.",
        durationMinutes: 35,
        price: 7500,
        icon: "HeartHandshake",
        badge: "Advanced Diagnostic",
        preparationInstructions: "Bring past ECGs and echo reports if previously conducted.",
        active: true,
        featured: false,
      },
      {
        name: "Pediatric Consultation & Vaccination",
        category: "Pediatrics",
        description: "Growth milestones audit, dietary plan, physical pediatric exam, and government/EPI certified vaccination.",
        durationMinutes: 20,
        price: 2500,
        icon: "Baby",
        badge: "Child Care",
        preparationInstructions: "Bring child's official immunization card.",
        active: true,
        featured: true,
      },
      {
        name: "Complete Eye & Vision Examination",
        category: "Ophthalmology",
        description: "Computerized Auto-refraction, slit-lamp microscope examination, intraocular pressure check, and prescription glasses testing.",
        durationMinutes: 25,
        price: 3000,
        icon: "Eye",
        badge: "Precision",
        preparationInstructions: "Bring current spectacles and contact lenses if in use.",
        active: true,
        featured: false,
      },
      {
        name: "Targeted Physiotherapy Session",
        category: "Physiotherapy",
        description: "Manual joint mobilization, therapeutic ultrasound, dry needling, postural realignment, and muscle strengthening.",
        durationMinutes: 45,
        price: 2200,
        icon: "Footprints",
        badge: "Rehab",
        preparationInstructions: "Wear flexible, comfortable sports attire or loose pants.",
        active: true,
        featured: true,
      },
      {
        name: "Stroke & Spinal Rehab Program",
        category: "Physiotherapy",
        description: "Intensive neuro-muscular gait training, balance recovery, and neuromuscular re-education for post-stroke mobility.",
        durationMinutes: 60,
        price: 3500,
        icon: "Dumbbell",
        badge: "Specialized",
        preparationInstructions: "Patient should be accompanied by an attendant.",
        active: true,
        featured: false,
      },
      {
        name: "Minor Surgical OPD Procedure",
        category: "General Surgery",
        description: "Excisions of sebaceous cysts, lipomas, ingrown toenail wedge resection, or suture removal under local anesthesia.",
        durationMinutes: 40,
        price: 7000,
        icon: "Scissors",
        badge: "Day Care",
        preparationInstructions: "Follow specific fasting instructions given upon scheduling.",
        active: true,
        featured: false,
      },
      {
        name: "Routine Diagnostic Blood Panel (CBC + ESR)",
        category: "Diagnostics",
        description: "Certified automated laboratory testing for anemia, systemic infection, platelets, and acute inflammatory markers.",
        durationMinutes: 15,
        price: 1500,
        icon: "TestTube",
        badge: "Quick Results",
        preparationInstructions: "No prior fasting necessary.",
        active: true,
        featured: false,
      },
    ];

    const insertedServices = await db.insert(services).values(servicesData).returning();

    // 5. Patients (30 Patients with realistic Pakistani demographic data)
    const patientsData = [
      {
        mrn: "MRN-2026-1001",
        name: "Tariq Mahmood",
        phone: "+92 300 4567891",
        email: "tariq.mahmood@example.com",
        gender: "Male",
        age: 52,
        bloodGroup: "B+",
        address: "House 14, Street 3, Model Town, Lahore",
        city: "Lahore",
        emergencyContact: "+92 300 4567890 (Son - Saad)",
        allergies: "Penicillin",
        medicalHistory: "Type 2 Diabetes, Mild Hypertension for 6 years",
        totalVisits: 4,
        outstandingBalance: 0,
      },
      {
        mrn: "MRN-2026-1002",
        name: "Bushra Parveen",
        phone: "+92 321 9876543",
        email: "bushra.p@example.com",
        gender: "Female",
        age: 44,
        bloodGroup: "O+",
        address: "Flat 202, Al-Hafeez Heights, Gulberg, Lahore",
        city: "Lahore",
        emergencyContact: "+92 321 9876544 (Husband - Naveed)",
        allergies: "Sulfa drugs",
        medicalHistory: "Hypothyroidism on Thyroxine 50mcg",
        totalVisits: 3,
        outstandingBalance: 0,
      },
      {
        mrn: "MRN-2026-1003",
        name: "Ali Hassan Cheema",
        phone: "+92 333 1122334",
        email: "ali.cheema@example.com",
        gender: "Male",
        age: 28,
        bloodGroup: "A+",
        address: "House 88, Sector Y, DHA Phase 3, Lahore",
        city: "Lahore",
        emergencyContact: "+92 333 1122330 (Father - M. Cheema)",
        allergies: "None",
        medicalHistory: "Sports injury (ACL sprain right knee)",
        totalVisits: 5,
        outstandingBalance: 0,
      },
      {
        mrn: "MRN-2026-1004",
        name: "Sadia Naveed",
        phone: "+92 345 5566778",
        email: "sadia.n@example.com",
        gender: "Female",
        age: 33,
        bloodGroup: "O-",
        address: "House 102, PCSIR Phase 2, Lahore",
        city: "Lahore",
        emergencyContact: "+92 345 5566770 (Brother - Salman)",
        allergies: "Aspirin",
        medicalHistory: "Adult Hormonal Acne, PCOD",
        totalVisits: 2,
        outstandingBalance: 0,
      },
      {
        mrn: "MRN-2026-1005",
        name: "Kamran Akram",
        phone: "+92 301 8899001",
        email: "kamran.akram@example.com",
        gender: "Male",
        age: 61,
        bloodGroup: "AB+",
        address: "House 24, Block G, Johar Town, Lahore",
        city: "Lahore",
        emergencyContact: "+92 301 8899000 (Wife - Nasreen)",
        allergies: "None",
        medicalHistory: "Coronary Artery Disease, Stent placed in 2023",
        totalVisits: 6,
        outstandingBalance: 0,
      },
      {
        mrn: "MRN-2026-1006",
        name: "Fatima Zahra",
        phone: "+92 312 4433221",
        email: "fatima.z@example.com",
        gender: "Female",
        age: 24,
        bloodGroup: "B-",
        address: "House 17, Cavalry Ground, Lahore Cantt",
        city: "Lahore",
        emergencyContact: "+92 312 4433220 (Mother - Rubina)",
        allergies: "Dust, Pollen",
        medicalHistory: "Allergic Rhinitis, Migraine",
        totalVisits: 2,
        outstandingBalance: 0,
      },
      {
        mrn: "MRN-2026-1007",
        name: "Bilal Zubair",
        phone: "+92 302 7766554",
        email: "bilal.z@example.com",
        gender: "Male",
        age: 39,
        bloodGroup: "O+",
        address: "House 312, Sector C, Bahria Town, Lahore",
        city: "Lahore",
        emergencyContact: "+92 302 7766550 (Spouse - Aiman)",
        allergies: "None",
        medicalHistory: "Dental Caries, Lower Left Molar Root Canal",
        totalVisits: 3,
        outstandingBalance: 0,
      },
      {
        mrn: "MRN-2026-1008",
        name: "Rabia Munir",
        phone: "+92 322 3344556",
        email: "rabia.m@example.com",
        gender: "Female",
        age: 29,
        bloodGroup: "A+",
        address: "Apartment 4B, Askari 11, Lahore",
        city: "Lahore",
        emergencyContact: "+92 322 3344550 (Husband - Usman)",
        allergies: "Nickel (skin contact)",
        medicalHistory: "Post-pregnancy skin hyperpigmentation",
        totalVisits: 3,
        outstandingBalance: 0,
      },
      {
        mrn: "MRN-2026-1009",
        name: "Imran Aslam",
        phone: "+92 334 9988776",
        email: "imran.aslam@example.com",
        gender: "Male",
        age: 47,
        bloodGroup: "B+",
        address: "House 45, Shadman 1, Lahore",
        city: "Lahore",
        emergencyContact: "+92 334 9988770 (Brother - Farooq)",
        allergies: "None",
        medicalHistory: "Lumbar Disc Herniation L4-L5, Sciatica",
        totalVisits: 7,
        outstandingBalance: 0,
      },
      {
        mrn: "MRN-2026-1010",
        name: "Nadia Shah",
        phone: "+92 300 2233445",
        email: "nadia.shah@example.com",
        gender: "Female",
        age: 38,
        bloodGroup: "O+",
        address: "House 77, Garden Town, Lahore",
        city: "Lahore",
        emergencyContact: "+92 300 2233440 (Husband - Shahbaz)",
        allergies: "Ibuprofen",
        medicalHistory: "Chronic Gastritis, Vitamin D Deficiency",
        totalVisits: 2,
        outstandingBalance: 0,
      },
      {
        mrn: "MRN-2026-1011",
        name: "Muhammad Rizwan",
        phone: "+92 313 8877665",
        email: "rizwan.m@example.com",
        gender: "Male",
        age: 35,
        bloodGroup: "A-",
        address: "House 12, Gulshan-e-Ravi, Lahore",
        city: "Lahore",
        emergencyContact: "+92 313 8877660 (Father - Nazir)",
        allergies: "None",
        medicalHistory: "Computer vision syndrome, Myopia -2.5D",
        totalVisits: 2,
        outstandingBalance: 0,
      },
      {
        mrn: "MRN-2026-1012",
        name: "Ayesha Sohail",
        phone: "+92 323 1122445",
        email: "ayesha.sohail@example.com",
        gender: "Female",
        age: 6,
        bloodGroup: "B+",
        address: "House 9, Canal View Society, Lahore",
        city: "Lahore",
        emergencyContact: "+92 323 1122440 (Mother - Hira)",
        allergies: "Peanuts",
        medicalHistory: "Childhood seasonal asthma",
        totalVisits: 4,
        outstandingBalance: 0,
      },
      {
        mrn: "MRN-2026-1013",
        name: "Zafar Iqbal",
        phone: "+92 305 6655443",
        email: "zafar.iqbal@example.com",
        gender: "Male",
        age: 58,
        bloodGroup: "AB-",
        address: "House 19, Faisal Town, Lahore",
        city: "Lahore",
        emergencyContact: "+92 305 6655440 (Son - Waqas)",
        allergies: "None",
        medicalHistory: "Essential Hypertension, High Cholesterol",
        totalVisits: 5,
        outstandingBalance: 0,
      },
      {
        mrn: "MRN-2026-1014",
        name: "Hina Danish",
        phone: "+92 331 4455889",
        email: "hina.danish@example.com",
        gender: "Female",
        age: 31,
        bloodGroup: "O+",
        address: "House 56, Sector J, DHA Phase 5, Lahore",
        city: "Lahore",
        emergencyContact: "+92 331 4455880 (Spouse - Danish)",
        allergies: "None",
        medicalHistory: "Facial Melasma, routine aesthetic maintenance",
        totalVisits: 3,
        outstandingBalance: 0,
      },
      {
        mrn: "MRN-2026-1015",
        name: "Hamza Baig",
        phone: "+92 341 7788992",
        email: "hamza.baig@example.com",
        gender: "Male",
        age: 26,
        bloodGroup: "A+",
        address: "House 10, Allama Iqbal Town, Lahore",
        city: "Lahore",
        emergencyContact: "+92 341 7788990 (Father - Khalid)",
        allergies: "None",
        medicalHistory: "Shoulder impingement from weight training",
        totalVisits: 4,
        outstandingBalance: 0,
      },
      {
        mrn: "MRN-2026-1016",
        name: "Shazia Parveen",
        phone: "+92 300 9988112",
        email: "shazia.p@example.com",
        gender: "Female",
        age: 49,
        bloodGroup: "B+",
        address: "House 33, Tech Society, Canal Road, Lahore",
        city: "Lahore",
        emergencyContact: "+92 300 9988110 (Daughter - Anum)",
        allergies: "Ciprofloxacin",
        medicalHistory: "Knee Osteoarthritis grade 2",
        totalVisits: 3,
        outstandingBalance: 0,
      },
      {
        mrn: "MRN-2026-1017",
        name: "Rashid Mehmood",
        phone: "+92 321 6655112",
        email: "rashid.m@example.com",
        gender: "Male",
        age: 42,
        bloodGroup: "O+",
        address: "House 8, Jubilee Town, Lahore",
        city: "Lahore",
        emergencyContact: "+92 321 6655110 (Wife - Saima)",
        allergies: "None",
        medicalHistory: "GERD and mild liver steatosis",
        totalVisits: 2,
        outstandingBalance: 0,
      },
      {
        mrn: "MRN-2026-1018",
        name: "Maryam Fayyaz",
        phone: "+92 332 5544331",
        email: "maryam.f@example.com",
        gender: "Female",
        age: 27,
        bloodGroup: "A+",
        address: "House 91, Valancia Town, Lahore",
        city: "Lahore",
        emergencyContact: "+92 332 5544330 (Father - Fayyaz)",
        allergies: "None",
        medicalHistory: "Dental crowding, scheduled for clear aligners",
        totalVisits: 2,
        outstandingBalance: 0,
      },
      {
        mrn: "MRN-2026-1019",
        name: "Omer Farooq",
        phone: "+92 306 1122998",
        email: "omer.farooq@example.com",
        gender: "Male",
        age: 36,
        bloodGroup: "B+",
        address: "House 142, WAPDA Town, Lahore",
        city: "Lahore",
        emergencyContact: "+92 306 1122990 (Brother - Usman)",
        allergies: "None",
        medicalHistory: "Stress induced tension headaches",
        totalVisits: 1,
        outstandingBalance: 0,
      },
      {
        mrn: "MRN-2026-1020",
        name: "Sobia Rehman",
        phone: "+92 314 2233119",
        email: "sobia.r@example.com",
        gender: "Female",
        age: 51,
        bloodGroup: "O-",
        address: "House 27, Punjab Coop Housing Society, Lahore",
        city: "Lahore",
        emergencyContact: "+92 314 2233110 (Husband - Haroon)",
        allergies: "Sulfa",
        medicalHistory: "Hypertension, Osteopenia",
        totalVisits: 3,
        outstandingBalance: 0,
      },
      {
        mrn: "MRN-2026-1021",
        name: "Daniyal Waseem",
        phone: "+92 308 7766112",
        email: "daniyal.w@example.com",
        gender: "Male",
        age: 22,
        bloodGroup: "AB+",
        address: "House 5, Eden City, Lahore",
        city: "Lahore",
        emergencyContact: "+92 308 7766110 (Mother - Salma)",
        allergies: "None",
        medicalHistory: "Cystic acne vulgaris",
        totalVisits: 2,
        outstandingBalance: 0,
      },
      {
        mrn: "MRN-2026-1022",
        name: "Noreen Qasim",
        phone: "+92 324 8899221",
        email: "noreen.q@example.com",
        gender: "Female",
        age: 41,
        bloodGroup: "A+",
        address: "House 18, State Life Housing Society, Lahore",
        city: "Lahore",
        emergencyContact: "+92 324 8899220 (Spouse - Qasim)",
        allergies: "Penicillin",
        medicalHistory: "Cervical spondylosis with neck stiffness",
        totalVisits: 4,
        outstandingBalance: 0,
      },
      {
        mrn: "MRN-2026-1023",
        name: "Sheikh Khurram",
        phone: "+92 300 5544778",
        email: "khurram.sheikh@example.com",
        gender: "Male",
        age: 48,
        bloodGroup: "B+",
        address: "House 4, Gulberg 2, Lahore",
        city: "Lahore",
        emergencyContact: "+92 300 5544770 (Son - Hamza)",
        allergies: "None",
        medicalHistory: "Fatty liver grade 1, border-line HbA1c",
        totalVisits: 2,
        outstandingBalance: 0,
      },
      {
        mrn: "MRN-2026-1024",
        name: "Khadija Bibi",
        phone: "+92 335 1199887",
        email: "khadija.b@example.com",
        gender: "Female",
        age: 65,
        bloodGroup: "O+",
        address: "House 20, Samanabad, Lahore",
        city: "Lahore",
        emergencyContact: "+92 335 1199880 (Son - Asif)",
        allergies: "None",
        medicalHistory: "Bilateral Senile Cataract, Diabetic Retinopathy check",
        totalVisits: 3,
        outstandingBalance: 0,
      },
      {
        mrn: "MRN-2026-1025",
        name: "Zubair Ahmad",
        phone: "+92 301 3344112",
        email: "zubair.a@example.com",
        gender: "Male",
        age: 34,
        bloodGroup: "A-",
        address: "House 61, PCSIR Staff Colony, Lahore",
        city: "Lahore",
        emergencyContact: "+92 301 3344110 (Wife - Tehmina)",
        allergies: "None",
        medicalHistory: "Recurrent aphthous ulcers in mouth",
        totalVisits: 1,
        outstandingBalance: 0,
      },
      {
        mrn: "MRN-2026-1026",
        name: "Samina Kausar",
        phone: "+92 321 7711223",
        email: "samina.k@example.com",
        gender: "Female",
        age: 54,
        bloodGroup: "B+",
        address: "House 83, Canal Heights, Lahore",
        city: "Lahore",
        emergencyContact: "+92 321 7711220 (Husband - Javed)",
        allergies: "Aspirin",
        medicalHistory: "Frozen Shoulder (adhesive capsulitis) left side",
        totalVisits: 5,
        outstandingBalance: 0,
      },
      {
        mrn: "MRN-2026-1027",
        name: "Bilawal Shah",
        phone: "+92 302 9900114",
        email: "bilawal.shah@example.com",
        gender: "Male",
        age: 30,
        bloodGroup: "O+",
        address: "House 11, Green City, Lahore",
        city: "Lahore",
        emergencyContact: "+92 302 9900110 (Brother - Shahmir)",
        allergies: "None",
        medicalHistory: "Routine dental checkup and calculus clean",
        totalVisits: 1,
        outstandingBalance: 0,
      },
      {
        mrn: "MRN-2026-1028",
        name: "Amber Jamil",
        phone: "+92 333 4488221",
        email: "amber.j@example.com",
        gender: "Female",
        age: 37,
        bloodGroup: "AB-",
        address: "House 95, Sector E, Bahria Orchard, Lahore",
        city: "Lahore",
        emergencyContact: "+92 333 4488220 (Spouse - Jamil)",
        allergies: "None",
        medicalHistory: "Persistent eczema flare-up on hands",
        totalVisits: 2,
        outstandingBalance: 0,
      },
      {
        mrn: "MRN-2026-1029",
        name: "Hassan Raza Gardezi",
        phone: "+92 307 2233665",
        email: "hassan.gardezi@example.com",
        gender: "Male",
        age: 46,
        bloodGroup: "O+",
        address: "House 52, Main Gulberg, Lahore",
        city: "Lahore",
        emergencyContact: "+92 307 2233660 (Wife - Ayla)",
        allergies: "None",
        medicalHistory: "Chest palpitations under stress, normal echo",
        totalVisits: 2,
        outstandingBalance: 0,
      },
      {
        mrn: "MRN-2026-1030",
        name: "Tahira Batool",
        phone: "+92 342 1199334",
        email: "tahira.b@example.com",
        gender: "Female",
        age: 59,
        bloodGroup: "A+",
        address: "House 7, New Muslim Town, Lahore",
        city: "Lahore",
        emergencyContact: "+92 342 1199330 (Son - Mohsin)",
        allergies: "Diclofenac Sodium",
        medicalHistory: "Osteoarthritis knees, bilateral managed with physio",
        totalVisits: 4,
        outstandingBalance: 0,
      },
    ];

    const insertedPatients = await db.insert(patients).values(patientsData).returning();

    // 6. Appointments (50 Realistic Appointments with dates, doctors, statuses)
    // Get current year and month for dynamic realistic dates
    const now = new Date();
    const currentYear = now.getFullYear();
    const currentMonth = String(now.getMonth() + 1).padStart(2, "0");
    const todayDay = now.getDate();

    const statuses = ["Confirmed", "In Consultation", "Completed", "Pending", "Cancelled"];
    const times = ["09:00 AM", "09:30 AM", "10:00 AM", "10:30 AM", "11:00 AM", "11:30 AM", "12:00 PM", "02:00 PM", "02:30 PM", "03:00 PM", "03:30 PM", "04:00 PM", "05:00 PM", "05:30 PM", "06:00 PM"];
    const visitTypes = ["New Consultation", "Follow-up", "Routine Checkup", "Procedure"];

    const appointmentsData = [];
    for (let i = 1; i <= 50; i++) {
      const patient = insertedPatients[(i - 1) % insertedPatients.length];
      const doctor = insertedDoctors[(i - 1) % insertedDoctors.length];
      const service = insertedServices[(i - 1) % insertedServices.length];
      
      // Spread dates around today (-10 to +10 days)
      const dayOffset = (i % 21) - 10;
      const appDateObj = new Date(now.getTime() + dayOffset * 24 * 60 * 60 * 1000);
      const appDateStr = appDateObj.toISOString().split("T")[0];
      const timeSlot = times[i % times.length];
      
      let status = "Confirmed";
      if (dayOffset < -2) {
        status = i % 5 === 0 ? "Cancelled" : "Completed";
      } else if (dayOffset === 0) {
        status = i % 3 === 0 ? "In Consultation" : i % 2 === 0 ? "Confirmed" : "Completed";
      } else if (dayOffset > 0) {
        status = i % 4 === 0 ? "Pending" : "Confirmed";
      }

      appointmentsData.push({
        appointmentNumber: `MED-2026-${1000 + i}`,
        patientId: patient.id,
        patientName: patient.name,
        patientPhone: patient.phone,
        patientEmail: patient.email,
        patientGender: patient.gender,
        patientAge: patient.age,
        doctorId: doctor.id,
        serviceId: service.id,
        appointmentDate: appDateStr,
        appointmentTime: timeSlot,
        visitType: visitTypes[i % visitTypes.length],
        status: status,
        fee: doctor.fee,
        paymentStatus: status === "Completed" ? "Paid" : status === "Cancelled" ? "Refunded" : (i % 2 === 0 ? "Paid" : "Pending"),
        patientNotes: i % 2 === 0 ? "Patient requests evening consultation slot if possible." : "First time visiting the clinic.",
        doctorNotes: status === "Completed" ? "Patient advised dietary modifications, blood glucose monitoring, and follow-up in 4 weeks." : null,
        prescription: status === "Completed" ? "1. Tab Metformin 500mg BD after meals\n2. Tab Panadol 500mg SOS for pain\n3. Cap Vitamin D 200,000 IU once monthly" : null,
      });
    }

    await db.insert(appointments).values(appointmentsData);

    // 7. Leads / Inquiries (20 Leads)
    const leadsData = [
      { name: "Shahid Rafiq", phone: "+92 300 4455667", email: "shahid.r@example.com", serviceInterested: "HydraFacial Glow Treatment", source: "Website Form", status: "New", notes: "Inquired about Saturday appointment slots and package discount for wedding." },
      { name: "Fatima Jahangir", phone: "+92 321 8899112", email: "fatima.j@example.com", serviceInterested: "Dental Scaling & Polishing", source: "WhatsApp Click", status: "Contacted", notes: "Discussed tooth whitening and booked provisional slot for next Monday." },
      { name: "Mian Arshad", phone: "+92 333 7766554", email: "arshad.mian@example.com", serviceInterested: "Executive Health Checkup Package", source: "Website Form", status: "Converted", notes: "Confirmed for Tuesday fasting lab test at 8:30 AM." },
      { name: "Areeba Chaudhry", phone: "+92 345 1122338", email: "areeba.c@example.com", serviceInterested: "Clinical Dermatology Consultation", source: "WhatsApp Click", status: "New", notes: "Asking about treatment for severe cystic acne on cheeks." },
      { name: "Nadeem Ashraf", phone: "+92 301 9988776", email: "nadeem.a@example.com", serviceInterested: "2D Color Doppler Echocardiography", source: "Phone Call", status: "Contacted", notes: "Cardiologist referral from family physician. Asked about fasting requirement." },
      { name: "Zunaira Tariq", phone: "+92 312 3344556", email: "zunaira.t@example.com", serviceInterested: "Pediatric Consultation & Vaccination", source: "Website Form", status: "Converted", notes: "Booked vaccination appointment for 6-month infant." },
      { name: "Kashif Butt", phone: "+92 322 5566778", email: "kashif.butt@example.com", serviceInterested: "Targeted Physiotherapy Session", source: "Walk-in", status: "Converted", notes: "Suffering from gym shoulder pain. Attended initial consultation." },
      { name: "Mariam Gul", phone: "+92 334 1188990", email: "mariam.gul@example.com", serviceInterested: "Complete Eye & Vision Examination", source: "Website Form", status: "New", notes: "Looking for computer screen anti-fatigue prescription test." },
      { name: "Sikandar Hayat", phone: "+92 306 4433221", email: "sikandar.h@example.com", serviceInterested: "Root Canal Treatment", source: "WhatsApp Click", status: "Contacted", notes: "Has severe toothache in lower right molar; needs urgent appointment." },
      { name: "Aneela Shahzad", phone: "+92 315 6677889", email: "aneela.s@example.com", serviceInterested: "HydraFacial Glow Treatment", source: "Website Form", status: "New", notes: "Asked whether pregnant patients can undergo HydraFacial." },
      { name: "Waleed Anjum", phone: "+92 324 5544332", email: "waleed.a@example.com", serviceInterested: "Executive Health Checkup Package", source: "Phone Call", status: "Contacted", notes: "Corporate inquiry for 5 senior company executives." },
      { name: "Haleema Sadia", phone: "+92 336 8899001", email: "haleema.s@example.com", serviceInterested: "General Physician Consultation", source: "Website Form", status: "Converted", notes: "Persistent fever and weakness for 4 days." },
      { name: "Babar Azam Khan", phone: "+92 302 3322119", email: "babar.khan@example.com", serviceInterested: "Targeted Physiotherapy Session", source: "WhatsApp Click", status: "New", notes: "Sciatica lower back pain radiating down left thigh." },
      { name: "Sumaira Qadir", phone: "+92 341 9988114", email: "sumaira.q@example.com", serviceInterested: "Cosmetic Dental Fillings", source: "Website Form", status: "Contacted", notes: "Wants aesthetic gap closure in upper front incisors." },
      { name: "Farooq Dar", phone: "+92 300 6677112", email: "farooq.dar@example.com", serviceInterested: "Cardiology Consultation & ECG", source: "Phone Call", status: "Converted", notes: "Follow-up hypertension visit after medication adjustment." },
      { name: "Rubab Fatima", phone: "+92 321 4455883", email: "rubab.f@example.com", serviceInterested: "Clinical Dermatology Consultation", source: "WhatsApp Click", status: "New", notes: "Inquiring about melasma chemical peel packages." },
      { name: "Junaid Jamshed Jr.", phone: "+92 332 7788119", email: "junaid.j@example.com", serviceInterested: "Teeth Scaling & Polishing", source: "Website Form", status: "Contacted", notes: "Wants afternoon scaling appointment on Saturday." },
      { name: "Tahira Yasmin", phone: "+92 307 8811223", email: "tahira.y@example.com", serviceInterested: "Pediatric Consultation & Vaccination", source: "Walk-in", status: "Converted", notes: "Enrolled in yearly child development checkup schedule." },
      { name: "Asadullah Chohan", phone: "+92 313 5566990", email: "asad.chohan@example.com", serviceInterested: "Minor Surgical OPD Procedure", source: "Website Form", status: "New", notes: "Sebaceous cyst on right shoulder; desires same-day excision." },
      { name: "Nazia Pervez", phone: "+92 346 1122557", email: "nazia.pervez@example.com", serviceInterested: "Complete Eye & Vision Examination", source: "WhatsApp Click", status: "Contacted", notes: "Elderly mother vision blurred; checked cataract consultation hours." },
    ];

    await db.insert(leads).values(leadsData);

    // 8. Reviews (10 High Quality Reviews)
    const reviewsData = [
      {
        patientName: "Engr. Tariq Mahmood",
        rating: 5,
        treatment: "Executive Health Checkup & Cardiology",
        doctorName: "Dr. Farhan Malik",
        comment: "Outstanding experience at Medicare Plus! The clinic environment is as clean and well-organized as private hospitals abroad in Dubai. Dr. Farhan explained my ECG and echo test with immense patience. Reception staff made the billing seamless.",
        city: "Lahore",
        published: true,
      },
      {
        patientName: "Sadia Naveed",
        rating: 5,
        treatment: "HydraFacial Glow & Dermatology",
        doctorName: "Dr. Zainab Tariq",
        comment: "Dr. Zainab is exceptionally skilled. She listened to my skin concerns and didn't push unnecessary expensive products. The HydraFacial gave my skin an unbelievable glow for my brother's wedding without any redness. Highly recommend!",
        city: "Lahore",
        published: true,
      },
      {
        patientName: "Bilal Zubair",
        rating: 5,
        treatment: "Painless Root Canal & Crown",
        doctorName: "Dr. Muhammad Bilal",
        comment: "I had extreme dental anxiety, but Dr. Bilal made the root canal literally 100% painless. The dental suite has the latest digital sensors and calming ambiance. Easily the best dentist in Gulberg.",
        city: "Lahore",
        published: true,
      },
      {
        patientName: "Kamran Akram",
        rating: 5,
        treatment: "Cardiac Consultation",
        doctorName: "Dr. Farhan Malik",
        comment: "I have been visiting Dr. Farhan for 2 years post-angioplasty. His preventive medicine approach and continuous monitoring kept my blood pressure strictly within healthy limits. 5 stars!",
        city: "Lahore",
        published: true,
      },
      {
        patientName: "Fatima Zahra",
        rating: 5,
        treatment: "Physiotherapy & Dry Needling",
        doctorName: "Dr. Fatima Noor",
        comment: "Suffered from agonizing cervical neck spasm from IT desk work. In just three sessions with Dr. Fatima Noor, my neck range of motion is completely restored. Very professional clinic!",
        city: "Lahore",
        published: true,
      },
      {
        patientName: "Ali Hassan Cheema",
        rating: 4,
        treatment: "Sports Knee Rehabilitation",
        doctorName: "Dr. Fatima Noor",
        comment: "Great facility with modern rehabilitation machines. The ultrasound and muscle stimulation helped my ligament recovery significantly. Very punctual appointment scheduling.",
        city: "Lahore",
        published: true,
      },
      {
        patientName: "Bushra Parveen",
        rating: 5,
        treatment: "General Health Consultation",
        doctorName: "Dr. Ayesha Siddiqui",
        comment: "Dr. Ayesha is compassionate, polite, and extremely thorough in examining test reports. She explained why my thyroid dosage needed adjustment in simple Urdu so I could understand clearly.",
        city: "Lahore",
        published: true,
      },
      {
        patientName: "Hina Danish",
        rating: 5,
        treatment: "Pediatric Vaccination & Checkup",
        doctorName: "Dr. Sana Qureshi",
        comment: "Dr. Sana is wonderful with babies! My 8-month daughter didn't even cry during the vaccine shot. Clean play area in the waiting lobby also kept the kids entertained.",
        city: "Lahore",
        published: true,
      },
      {
        patientName: "Muhammad Rizwan",
        rating: 5,
        treatment: "Computerized Eye Checkup",
        doctorName: "Dr. Usman Khalid",
        comment: "Quick, efficient, and very precise refraction test. The clinic got my new blue-cut spectacle prescription right on the first try. No waiting time thanks to online booking!",
        city: "Lahore",
        published: true,
      },
      {
        patientName: "Rashid Mehmood",
        rating: 4,
        treatment: "Ultrasound & Minor Surgery",
        doctorName: "Dr. Hamza Raza",
        comment: "Dr. Hamza performed a minor cyst excision under local anesthesia with utmost care. Suture healed flawlessly with virtually no scar. Superb nursing team.",
        city: "Lahore",
        published: true,
      },
    ];

    await db.insert(reviews).values(reviewsData);

    // 9. Blog Posts (12 Realistic Medical Articles)
    const blogData = [
      {
        slug: "understanding-hypertension-silent-killer-pakistan",
        title: "Understanding Hypertension: Managing the Silent Killer in Pakistan",
        category: "Cardiology",
        authorName: "Dr. Farhan Malik",
        authorRole: "Consultant Interventional Cardiologist",
        readTime: "5 min read",
        summary: "Over 46% of adults in Pakistan suffer from high blood pressure without obvious symptoms. Learn early warning indicators, dietary shifts, and when to seek urgent cardiology care.",
        content: `Hypertension is frequently termed the 'silent killer' because it can quietly damage your blood vessels, kidneys, and heart muscle for years before manifesting overt symptoms.\n\nIn Pakistan, cultural dietary habits rich in refined sodium (common salt), trans-fats from hydrogenated cooking ghee, and rising sedentary lifestyle habits have significantly elevated cardiovascular risk among individuals as young as 30.\n\n### Key Warning Indicators\n- Early morning throbbing occipital headaches\n- Occasional unprovoked dizziness or blurred vision\n- Mild shortness of breath during routine stair climbing\n- Irregular heart palpitations or chest tightness\n\n### Practical Lifestyle Interventions\n1. **Reduce Daily Sodium:** Limit table salt and avoid processed snacks, papadum, and pre-packaged pickles.\n2. **Daily Brisk Walking:** At least 30 minutes of aerobic exercise 5 days a week.\n3. **Regular Monitoring:** Check your blood pressure weekly with a calibrated upper-arm digital monitor.\n4. **Routine Clinical Review:** Schedule an annual consultation and resting ECG with your cardiologist.`,
        published: true,
        views: 340,
      },
      {
        slug: "managing-type-2-diabetes-during-ramadan",
        title: "Managing Type-2 Diabetes & Blood Sugar Fluctuations During Fasting",
        category: "General Medicine",
        authorName: "Dr. Ayesha Siddiqui",
        authorRole: "Senior Consultant Physician",
        readTime: "6 min read",
        summary: "Essential medical guidelines on medication dosage adjustments, safe Suhoor & Iftar nutrition, and hypoglycemia alert thresholds for diabetic patients.",
        content: `Fasting safely with diabetes requires proactive clinical planning. Before fasting, every diabetic patient should consult their physician for risk stratification.\n\n### Essential Fasting Guidelines\n- Never skip Suhoor (Sehri). Include slow-release complex carbohydrates like whole wheat roti, oats, and protein like boiled eggs.\n- Break fast with 1 small date and ample plain water rather than concentrated sugary sherbets.\n- Check blood sugar levels immediately if experiencing shakiness, sweating, confusion, or severe dizziness. Break the fast immediately if blood glucose falls below 70 mg/dL.\n\nAlways adjust your evening oral hypoglycemic or insulin doses only under the direct supervision of your consulting doctor.`,
        published: true,
        views: 520,
      },
      {
        slug: "teeth-whitening-vs-scaling-myths-debunked",
        title: "Teeth Scaling vs. Whitening: Common Dental Myths Debunked",
        category: "Dental Care",
        authorName: "Dr. Muhammad Bilal",
        authorRole: "Consultant Dental Surgeon",
        readTime: "4 min read",
        summary: "Does ultrasonic teeth scaling make your teeth loose or thin? Our dental surgeon clarifies the truth behind modern ultrasonic dental hygiene.",
        content: `One of the most persistent myths in Pakistani dentistry is the fear that routine scaling and cleaning weakens teeth or erodes protective enamel.\n\n### The Clinical Truth\nUltrasonic scalers vibrate at microscopic frequencies to dislodge hardened bacterial calculus (tartar) that manual toothbrushes cannot budge. Calculus harbor colonies of destructive bacteria that eat away supporting jaw bone and cause gingivitis.\n\n- Scaling does NOT thin tooth enamel.\n- Mild temporary cold sensitivity post-scaling is normal as clean root surfaces adjust to temperature changes.\n- Regular 6-month cleaning prevents costly root canals, periodontitis, and loose teeth down the road.`,
        published: true,
        views: 290,
      },
      {
        slug: "treating-adult-cystic-acne-and-melasma-pakistani-skin",
        title: "Treating Adult Cystic Acne & Melasma in South Asian Skin Types",
        category: "Dermatology",
        authorName: "Dr. Zainab Tariq",
        authorRole: "Consultant Dermatologist",
        readTime: "6 min read",
        summary: "Why South Asian skin (Fitzpatrick types III-V) is prone to stubborn post-inflammatory hyperpigmentation, and how clinical dermatological treatments provide permanent relief.",
        content: `South Asian skin contains abundant melanocytes that react vigorously to inflammation, making acne blemishes leave dark stubborn spots (PIH) that persist for months.\n\n### Effective Clinical Approaches\n- **Targeted Topical Actives:** Azelaic acid, niacinamide, and prescription retinoids under medical guidance.\n- **Gentle Chemical Peels:** Low-percentage Mandelic or Glycolic peels tailored to avoid triggering hyperpigmentation.\n- **Broad-Spectrum Sun Protection:** Daily mineral sunscreen with SPF 50+ is mandatory even when staying indoors near sunny windows.\n- Avoid harsh over-the-counter bleaching creams containing unchecked mercury or potent steroids that cause irreversible skin thinning.`,
        published: true,
        views: 610,
      },
      {
        slug: "essential-childhood-vaccination-schedule-pakistan",
        title: "The Essential Childhood Immunization Schedule in Pakistan: A Parent's Guide",
        category: "Pediatrics",
        authorName: "Dr. Sana Qureshi",
        authorRole: "Pediatric Specialist",
        readTime: "5 min read",
        summary: "A complete walkthrough of EPI government immunization and supplementary optional vaccines (Rotavirus, Hepatitis A, Typhoid Conjugate, Chickenpox) for infants.",
        content: `Protecting your child from debilitating vaccine-preventable illnesses begins at birth.\n\n### Core Immunization Milestones\n- **At Birth:** BCG (Tuberculosis) and OPV-0 (Oral Polio)\n- **6, 10, and 14 Weeks:** Pentavalent (Diphtheria, Tetanus, Pertussis, Hep B, Hib), Pneumococcal, and Rotavirus\n- **9 and 15 Months:** Measles-Rubella (MR) Vaccine\n- **Supplementary Vaccines:** Highly advised by the Pakistan Pediatric Association: Typhoid Conjugate Vaccine (TCV), Varicella (Chickenpox), and Hepatitis A.\n\nKeep your child's immunization card secure and bring it to every clinical wellness visit.`,
        published: true,
        views: 410,
      },
      {
        slug: "erasing-digital-eye-strain-20-20-20-rule",
        title: "Combating Digital Eye Strain in the Remote Work Era: The 20-20-20 Rule",
        category: "Ophthalmology",
        authorName: "Dr. Usman Khalid",
        authorRole: "Senior Ophthalmologist",
        readTime: "4 min read",
        summary: "Prolonged screen exposure reduces natural blink rates by 60%. Learn how to protect your eyes from dryness, headaches, and optical fatigue.",
        content: `With laptop and smartphone screen time exceeding 8 hours daily for most professionals, dry eye syndrome and accommodative spasm are reaching epidemic proportions.\n\n### The 20-20-20 Protocol\nEvery **20 minutes**, look away from your screen at an object located at least **20 feet** away for at least **20 seconds**. This allows the ciliary muscles inside your eyes to relax.\n\n### Ergonomic Fixes\n- Position monitor so the top edge is at or slightly below eye level.\n- Keep screen brightness matched to surrounding room ambient light.\n- Use preservative-free lubricating artificial tears if experiencing gritty burning sensations.`,
        published: true,
        views: 310,
      },
      {
        slug: "desk-job-ergonomics-and-sciatica-relief",
        title: "Relieving Desk Job Back Pain & Sciatica: A Physical Therapist's Advice",
        category: "Physiotherapy",
        authorName: "Dr. Fatima Noor",
        authorRole: "Doctor of Physical Therapy",
        readTime: "5 min read",
        summary: "Ergonomic chair setups, pelvic tilt exercises, and daily stretching routines to prevent disc herniation and tingling nerve pain.",
        content: `Sitting continuously for extended periods increases lumbar intradiscal pressure by over 140% compared to standing.\n\n### Warning Signs of Sciatic Nerve Irritation\n- Sharp electric pain radiating from lower back through the buttocks down to the calf or foot.\n- Numbness or tingling sensation in toes.\n- Increased discomfort when bending forward or sitting in soft couches.\n\n### Preventive Exercises\n1. Cat-Camel spinal mobility stretches every morning.\n2. Piriformis and hamstring stretches done while seated at work.\n3. Core stabilization planks to brace the lumbar spine.\nConsult our physiotherapy department for personalized biomechanical evaluation and dry needling therapy.`,
        published: true,
        views: 450,
      },
      {
        slug: "healthy-heart-diet-traditional-pakistani-cooking",
        title: "Heart-Healthy Pakistani Cuisine: Swapping Ghee for Healthy Oils",
        category: "Cardiology",
        authorName: "Dr. Farhan Malik",
        authorRole: "Consultant Cardiologist",
        readTime: "5 min read",
        summary: "You don't have to give up your favorite Karahi or Daal! Learn simple culinary modifications to lower LDL bad cholesterol while preserving rich traditional flavor.",
        content: `Traditional Pakistani culinary culture celebrates deep frying and heavy gravies with floating oil. By making conscious ingredient substitutions, you can slash saturated fats dramatically.\n\n### Smart Kitchen Swaps\n- Replace Banaspati Ghee with cold-pressed mustard oil, olive oil, or sunflower oil in controlled measurements (1 tablespoon per dish).\n- Increase garlic, ginger, turmeric, and cumin; these natural anti-inflammatory spices boost cardiovascular resilience.\n- Prefer skinless chicken and lentils over fatty red meats (mutton/beef) to keep lipid profiles balanced.`,
        published: true,
        views: 380,
      },
      {
        slug: "post-pregnancy-hair-loss-what-is-normal",
        title: "Postpartum Hair Loss (Telogen Effluvium): What Is Normal & When to Treat",
        category: "Dermatology",
        authorName: "Dr. Zainab Tariq",
        authorRole: "Consultant Dermatologist",
        readTime: "4 min read",
        summary: "Sudden hair shedding 3 to 4 months after childbirth can be distressing. Learn about hormonal shifts, ferritin levels, and therapeutic PRP treatments.",
        content: `During pregnancy, elevated estrogen levels keep hair follicles locked in the growth (anagen) phase. Following delivery, estrogen levels normalize rapidly, triggering simultaneous shedding of thousands of hairs.\n\n### When to Consult a Dermatologist\n- If shedding persists beyond 6 to 9 months postpartum.\n- If you notice focal bald patches or widening hair partings.\n- Blood screening for Serum Ferritin, Vitamin D3, and TSH is recommended to rule out underlying postpartum thyroiditis or iron-deficiency anemia.`,
        published: true,
        views: 490,
      },
      {
        slug: "oral-hygiene-for-children-preventing-early-cavities",
        title: "Pediatric Dental Health: Protecting Milk Teeth from Nursing Bottle Decay",
        category: "Dental Care",
        authorName: "Dr. Muhammad Bilal",
        authorRole: "Consultant Dental Surgeon",
        readTime: "4 min read",
        summary: "Why milk teeth matter just as much as permanent teeth, and how to prevent painful early childhood caries from bedtime milk bottles.",
        content: `A common misconception is that baby teeth don't require care because they will fall out anyway. In reality, premature loss of milk teeth causes severe crowding, speech difficulties, and nutritional deficiencies.\n\n### Key Tips for Parents\n- Never let your toddler sleep with a bottle containing milk, juices, or sweetened beverages.\n- Wipe infant gums with a clean damp gauze after every feed.\n- Introduce soft-bristled toothbrushing with a smear of child-safe toothpaste as soon as the first tooth erupts around 6 months.`,
        published: true,
        views: 260,
      },
      {
        slug: "geriatric-health-preventing-falls-elderly-parents",
        title: "Elderly Care & Fall Prevention: Keeping Aging Parents Safe at Home",
        category: "General Medicine",
        authorName: "Dr. Ayesha Siddiqui",
        authorRole: "Senior Consultant Physician",
        readTime: "5 min read",
        summary: "Practical modifications in Pakistani households to prevent catastrophic hip fractures, along with bone density (DEXA) recommendations.",
        content: `Falls in seniors over age 65 are the leading cause of debilitating hip fractures and loss of independence.\n\n### Home Safety Checklist\n- Install non-slip rubber mats and sturdy grab bars inside bathrooms and near toilets.\n- Ensure adequate night lights in hallways between bedrooms and washrooms.\n- Remove loose floor rugs and clutter from walking pathways.\n- Annual bone mineral density (DEXA) scans and calcium/Vitamin D supplementation are crucial for postmenopausal women.`,
        published: true,
        views: 320,
      },
      {
        slug: "understanding-laparoscopic-gallbladder-surgery",
        title: "Laparoscopic Gallbladder Surgery (Cholecystectomy): What to Expect",
        category: "General Surgery",
        authorName: "Dr. Hamza Raza",
        authorRole: "Consultant Laparoscopic Surgeon",
        readTime: "5 min read",
        summary: "How modern keyhole surgery makes gallbladder stone removal a safe, virtually scarless, same-day or 24-hour procedure with rapid recovery.",
        content: `Gallstones causing painful biliary colic or inflammation (cholecystitis) are one of the most common surgical presentations in adult women and men in Pakistan.\n\n### The Laparoscopic Advantage\nInstead of a large 15cm abdominal incision, laparoscopic surgery utilizes 3 to 4 tiny keyhole incisions (0.5 to 1 cm) through which high-definition cameras and micro-instruments operate.\n\n- Significantly reduced post-operative pain.\n- Patients typically walk within 4 hours and return home the next morning.\n- Return to light work activities within 5 to 7 days.`,
        published: true,
        views: 390,
      },
    ];

    await db.insert(blogPosts).values(blogData);

    // 10. FAQs (15 Categorized Realistic FAQs)
    const faqsData = [
      {
        question: "How do I book an appointment at Medicare Plus?",
        answer: "You can book instantly using our online 4-step booking form on this website, send us a message on WhatsApp at +92 300 1234567, or call our clinical reception desk at +92 42 3578 9000. You will receive an immediate SMS and booking confirmation code.",
        category: "Appointments",
        orderNumber: 1,
        active: true,
      },
      {
        question: "Can I get a same-day consultation with a specialist?",
        answer: "Yes! We keep reserved emergency and urgent walk-in slots for all our consulting physicians, pediatricians, and dentists every day. Same-day appointments can be reserved directly online or via WhatsApp before 2:00 PM.",
        category: "Appointments",
        orderNumber: 2,
        active: true,
      },
      {
        question: "What payment methods are accepted at the clinic?",
        answer: "We accept Cash (PKR), all major Pakistani Debit & Credit Cards (Visa, MasterCard, PayPak), JazzCash, EasyPaisa, and direct Raast / 1Link online bank transfers at our billing counters.",
        category: "Pricing & Billing",
        orderNumber: 3,
        active: true,
      },
      {
        question: "Do you accept health insurance and corporate panel cards?",
        answer: "Yes, Medicare Plus is paneled with leading healthcare insurance providers including Jubilee Life, EFU General, Adamjee Insurance, State Life, and Pak-Qatar Takaful. Direct cashless claims and itemized reimbursement receipts are provided.",
        category: "Pricing & Billing",
        orderNumber: 4,
        active: true,
      },
      {
        question: "What are your consultation fees?",
        answer: "Our consultation fees range from PKR 2,200 to PKR 4,000 depending on the medical specialist and department. A free follow-up review within 7 days is included for most general physician and pediatric consultations.",
        category: "Pricing & Billing",
        orderNumber: 5,
        active: true,
      },
      {
        question: "Where is the clinic located in Lahore?",
        answer: "Our primary flagship clinic is located at Plot 42-B, Main Boulevard, Gulberg III, Lahore, Pakistan (right near MM Alam Road). We provide free dedicated on-site valet parking and wheelchair access for all patients.",
        category: "Location & Timings",
        orderNumber: 6,
        active: true,
      },
      {
        question: "What are your emergency and OPD operating hours?",
        answer: "Our OPD clinics operate Monday through Friday from 8:00 AM to 10:00 PM, and Saturday from 9:00 AM to 8:00 PM. Emergency triage and urgent basic care is available 24 hours, 7 days a week.",
        category: "Location & Timings",
        orderNumber: 7,
        active: true,
      },
      {
        question: "Is dental treatment painful?",
        answer: "No. Our dental suites utilize computer-assisted painless local anesthesia, topical numbing gels, and ultrasonic instruments. Whether you need a simple filling or a complex root canal, patient comfort is our highest priority.",
        category: "Services",
        orderNumber: 8,
        active: true,
      },
      {
        question: "How long does a HydraFacial session take, and is there downtime?",
        answer: "A standard clinical HydraFacial takes approximately 45 to 60 minutes. There is zero downtime—you can apply makeup and return to work or social events immediately with a radiant, deeply hydrated glow.",
        category: "Services",
        orderNumber: 9,
        active: true,
      },
      {
        question: "Do I need to fast before lab tests or health checkups?",
        answer: "Routine tests like CBC and uric acid do not require fasting. However, Lipid Profile, Fasting Blood Glucose, and the Executive Health Checkup package require 10 to 12 hours of overnight water-only fasting. Our team will advise you upon booking.",
        category: "Diagnostics & Labs",
        orderNumber: 10,
        active: true,
      },
      {
        question: "Can I reschedule or cancel my appointment?",
        answer: "Yes, you can easily reschedule or cancel your appointment anytime using our online Patient Portal by entering your Appointment Number (e.g. MED-2026-1001), or by sending a quick WhatsApp text to our reception desk at least 2 hours in advance.",
        category: "Appointments",
        orderNumber: 11,
        active: true,
      },
      {
        question: "How are medical records and patient privacy protected?",
        answer: "All patient files, diagnostic scans, and medical history are encrypted in our HIPAA-compliant Electronic Health Record (EHR) system. Your data is strictly confidential and never shared without your written authorization.",
        category: "General",
        orderNumber: 12,
        active: true,
      },
      {
        question: "Do you offer home sample collection for lab tests?",
        answer: "Yes! Our certified phlebotomists provide sterile, cold-chain home blood sample collection across Lahore. Call our lab helpline or WhatsApp us to schedule a phlebotomist at your doorstep.",
        category: "Diagnostics & Labs",
        orderNumber: 13,
        active: true,
      },
      {
        question: "Are your doctors PMDC / PMC certified?",
        answer: "Every doctor and consultant practicing at Medicare Plus is verified and registered with the Pakistan Medical Commission (PMC / PMDC) and holds post-graduate fellowships (FCPS, MRCP, FRCS, RDS) from accredited royal colleges and universities.",
        category: "General",
        orderNumber: 14,
        active: true,
      },
      {
        question: "Can this management software be customized for other clinics?",
        answer: "Yes! This system is powered by WordbitX Software Company and can be fully customized for dental clinics, dermatology centers, eye clinics, physiotherapy rehab centers, pediatric practices, and multi-specialty hospitals with custom branding, domains, and workflows.",
        category: "General",
        orderNumber: 15,
        active: true,
      },
    ];

    await db.insert(faqs).values(faqsData);

    console.log("Successfully seeded database with all required clinic entities!");
  } catch (error) {
    console.error("Error in seedDatabase:", error);
  }
}
